---
title: "Shiny App Project"
author: "Leonardo Simioni"
date: "2022-09-28"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Shiny App

This project consists of creating a basic Shiny application. This app has two tabs and interactive visualizations. The data has information about the stats of the different drivers from the Mario Kart 8 game

Data source: https://www.kaggle.com/datasets/barelydedicated/mariokart8?select=characters.csv

## ui.R code {.smaller}
characters <- read.csv("data/characters.csv")

intro_panel <- tabPanel(
  "Introduction",
  
  titlePanel("Shiny App"),
  
select_values <- colnames(characters)
select_values <- select_values[! select_values %in% c('Character', 'Class')] # remove unwanted columns
sidebar_content <- sidebarPanel(
  selectInput(
    "y_var",
    label = "Y Variable",
    choices = select_values,
    selected = 'Speed'
  )
)

main_content <- mainPanel(
  plotOutput("plot")
)

second_panel <- tabPanel(
  "Visualization",
  titlePanel("Characteristics of Mario Kart 8 drivers"),
  p("Choose variables."),
  sidebarLayout(
    sidebar_content, main_content
  )
)

ui <- navbarPage(
  "Characteristics of Mario Kart 8 drivers",
  intro_panel,
  second_panel
)

## server.R code {.smaller}

library(ggplot2)

characters <- read.csv("data/characters.csv")


server <- function(input, output) {
  output$plot <- renderPlot({

        characters$Character <- factor(characters$Character, 
        levels = characters$Character[order(characters$Class)])
    
    ggplot(data=characters, aes_string(x='Character', y=input$y_var, fill="Class")) +
      geom_bar(stat="identity", width=0.8) +
      labs(x="Character", y=input$y_var) + coord_flip()
    
  })
}

## app.R code {.smaller}

library("shiny")
source("ui.R")
source("server.R")

shinyApp(ui = ui, server = server)
